test:priority_queue_test.o priority_queue.o
	g++ -g *.o -o test
priority_queue_test.o:priority_queue_test.cpp
	g++ -c priority_queue_test.cpp
priority_queue.o:priority_queue.cpp
	g++ -c priority_queue.cpp
